-- OpenCode Context Bridge
-- Structured relay schema. Raw code/logs/prompts do not belong here.

create schema if not exists context_bridge;

create table if not exists context_bridge.agent_state (
  project_id text not null,
  project_label text,
  session_id text not null,
  repository text,
  branch text not null,
  head_commit text,
  git_dirty boolean not null default false,
  changed_files jsonb not null default '[]'::jsonb,
  git_stats jsonb not null default '{}'::jsonb,
  status text not null check (status in ('working', 'idle', 'blocked')),
  goal text,
  current_task text,
  reason text,
  approach_summary text,
  important_details jsonb not null default '[]'::jsonb,
  recent_progress jsonb not null default '[]'::jsonb,
  decisions jsonb not null default '[]'::jsonb,
  decision_details jsonb not null default '[]'::jsonb,
  diagnostics jsonb not null default '[]'::jsonb,
  checks jsonb not null default '[]'::jsonb,
  current_problem text,
  problem_severity text check (problem_severity is null or problem_severity in ('info', 'minor', 'major', 'blocked')),
  next_step text,
  rolling_summary text,
  updated_at timestamptz not null default now(),
  primary key (project_id, session_id)
);

create index if not exists agent_state_project_updated_idx
  on context_bridge.agent_state (project_id, updated_at desc);

create table if not exists context_bridge.agent_runtime (
  project_id text not null,
  project_label text,
  session_id text not null,
  repository text,
  branch text not null,
  head_commit text,
  git_dirty boolean not null default false,
  changed_files jsonb not null default '[]'::jsonb,
  git_stats jsonb not null default '{}'::jsonb,
  status text not null check (status in ('working', 'idle', 'blocked')),
  current_action text,
  updated_at timestamptz not null default now(),
  primary key (project_id, session_id)
);

create index if not exists agent_runtime_project_updated_idx
  on context_bridge.agent_runtime (project_id, updated_at desc);

create table if not exists context_bridge.session_metadata (
  project_id text not null,
  project_label text,
  session_id text not null,
  repository text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_status text not null default 'idle' check (last_status in ('working', 'idle', 'blocked')),
  last_branch text,
  last_head_commit text,
  last_git_dirty boolean not null default false,
  closed_at timestamptz,
  primary key (project_id, session_id)
);

create index if not exists session_metadata_project_seen_idx
  on context_bridge.session_metadata (project_id, last_seen_at desc);

create table if not exists context_bridge.session_snapshots (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  repository text,
  branch text not null,
  head_commit text,
  git_dirty boolean not null default false,
  changed_files jsonb not null default '[]'::jsonb,
  git_stats jsonb not null default '{}'::jsonb,
  status text not null check (status in ('working', 'idle', 'blocked')),
  goal text,
  current_task text,
  reason text,
  approach_summary text,
  important_details jsonb not null default '[]'::jsonb,
  recent_progress jsonb not null default '[]'::jsonb,
  decisions jsonb not null default '[]'::jsonb,
  decision_details jsonb not null default '[]'::jsonb,
  diagnostics jsonb not null default '[]'::jsonb,
  checks jsonb not null default '[]'::jsonb,
  current_problem text,
  problem_severity text check (problem_severity is null or problem_severity in ('info', 'minor', 'major', 'blocked')),
  next_step text,
  rolling_summary text,
  captured_at timestamptz not null default now()
);

create index if not exists session_snapshots_project_captured_idx
  on context_bridge.session_snapshots (project_id, captured_at desc);
create index if not exists session_snapshots_session_captured_idx
  on context_bridge.session_snapshots (project_id, session_id, captured_at desc);

create table if not exists context_bridge.activity_events (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  event_type text not null check (event_type in ('tool_completed', 'tool_failed', 'session_idle', 'session_error', 'session_compacted')),
  category text not null check (category in ('read', 'write', 'search', 'execution', 'integration', 'other', 'session')),
  tool_name text,
  paths jsonb not null default '[]'::jsonb,
  outcome text check (outcome is null or outcome in ('success', 'error', 'idle')),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists activity_events_project_created_idx
  on context_bridge.activity_events (project_id, created_at desc);
create index if not exists activity_events_session_created_idx
  on context_bridge.activity_events (project_id, session_id, created_at desc);

create table if not exists context_bridge.decision_log (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  decision_key text not null,
  decision text not null,
  rationale text,
  state text not null default 'active' check (state in ('active', 'superseded')),
  branch text,
  head_commit text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (project_id, session_id, decision_key)
);

create index if not exists decision_log_project_seen_idx
  on context_bridge.decision_log (project_id, last_seen_at desc);

create table if not exists context_bridge.diagnostic_events (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  diagnostic_key text not null,
  category text,
  severity text not null check (severity in ('info', 'minor', 'major', 'blocked')),
  summary text not null,
  source text,
  retry_count integer check (retry_count is null or retry_count >= 0),
  branch text,
  head_commit text,
  created_at timestamptz not null default now()
);

create index if not exists diagnostic_events_project_created_idx
  on context_bridge.diagnostic_events (project_id, created_at desc);
create index if not exists diagnostic_events_key_created_idx
  on context_bridge.diagnostic_events (project_id, session_id, diagnostic_key, created_at desc);

create table if not exists context_bridge.validation_runs (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  branch text,
  head_commit text,
  kind text not null check (kind in ('test', 'build', 'lint', 'typecheck', 'validation')),
  name text not null,
  status text not null check (status in ('passed', 'failed', 'partial', 'skipped')),
  summary text,
  passed integer check (passed is null or passed >= 0),
  failed integer check (failed is null or failed >= 0),
  skipped integer check (skipped is null or skipped >= 0),
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists validation_runs_project_created_idx
  on context_bridge.validation_runs (project_id, created_at desc);
create index if not exists validation_runs_session_created_idx
  on context_bridge.validation_runs (project_id, session_id, created_at desc);

create table if not exists context_bridge.work_events (
  id bigint generated by default as identity primary key,
  project_id text not null,
  project_label text,
  session_id text not null,
  repository text,
  branch text not null,
  head_commit text,
  event_type text not null check (event_type in ('checkpoint', 'blocker', 'decision', 'milestone')),
  summary text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists work_events_project_created_idx
  on context_bridge.work_events (project_id, created_at desc);

create table if not exists context_bridge.browser_context (
  device_id text primary key,
  active_title text,
  active_url text,
  recent_tabs jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

-- Access control is role-based. Do not grant these tables to PUBLIC.
-- Roles and grants are managed by database/roles/*.sql.

comment on table context_bridge.agent_state is 'Latest AI-compressed semantic OpenCode context per project/session.';
comment on table context_bridge.agent_runtime is 'Small throttled runtime status per project/session; no raw logs or code.';
comment on table context_bridge.session_metadata is 'Lifecycle metadata for known OpenCode project sessions.';
comment on table context_bridge.session_snapshots is 'Append-only structured semantic context history; never raw prompts/logs/code.';
comment on table context_bridge.activity_events is 'Safe structured tool/session activity metadata without raw inputs or outputs.';
comment on table context_bridge.decision_log is 'Deduplicated semantic decisions and rationale per project/session.';
comment on table context_bridge.diagnostic_events is 'Append-only structured blocker/error summaries without raw logs.';
comment on table context_bridge.validation_runs is 'Structured test/build/lint/typecheck/validation summaries.';
comment on table context_bridge.work_events is 'Meaningful historical checkpoints, decisions and blockers, scoped by project.';
comment on table context_bridge.browser_context is 'Future minimal active/recent browser tab metadata.';
